export const addG = "add"
export const decreaseG = "decrease"
export const login = "login"
export const log="log"
export const USER_DATA="USER_DATA"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const ERROR_MSG = "ERROR_MSG"